const ACTIVITY = {
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  UPLOAD_FILE: 'UPLOAD_FILE',
  ADD_MEMBER: 'ADD_MEMBER',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  CONFIRM_SENTENCE: 'CONFIRM_SENTENCE',
};

module.exports = ACTIVITY;
