const LANGUAGE = {
  EN: 'en',
  VI: 'vi',
  Afrikaans: 'af',
  Albanian: 'sq',
  Amharic: 'am',
  Arabic: 'ar',
  Armenian: 'hy',
  Assamese: 'as',
  Aymara: 'ay',
  Azerbaijani: 'az',
  Bambara: 'bm',
  Basque: 'eu',
  Belarusian: 'be',
  Bengali: 'bn',
  Bhojpuri: 'bho',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Catalan: 'ca',
  Cebuano: 'ceb',
  Chichewa: 'ny',
  'Chinese (simplified)': 'zh-CN',
  'Chinese (traditional)': 'zh-TW',
  Corsican: 'co',
  Croatian: 'hr',
  Czech: 'cs',
  Danish: 'da',
  Dhivehi: 'dv',
  Dogri: 'doi',
  Dutch: 'nl',
  // 'English': 'en',
  Esperanto: 'eo',
  Estonian: 'et',
  Ewe: 'ee',
  Filipino: 'tl',
  Finnish: 'fi',
  French: 'fr',
  Frisian: 'fy',
  Galician: 'gl',
  Georgian: 'ka',
  German: 'de',
  Greek: 'el',
  Guarani: 'gn',
  Gujarati: 'gu',
  'Haitian creole': 'ht',
  Hausa: 'ha',
  Hawaiian: 'haw',
  Hebrew: 'iw',
  Hindi: 'hi',
  Hmong: 'hmn',
  Hungarian: 'hu',
  Icelandic: 'is',
  Igbo: 'ig',
  Ilocano: 'ilo',
  Indonesian: 'id',
  Irish: 'ga',
  Italian: 'it',
  Japanese: 'ja',
  Javanese: 'jw',
  Kannada: 'kn',
  Kazakh: 'kk',
  Khmer: 'km',
  Kinyarwanda: 'rw',
  Konkani: 'gom',
  Korean: 'ko',
  Krio: 'kri',
  'Kurdish (kurmanji)': 'ku',
  'Kurdish (sorani)': 'ckb',
  Kyrgyz: 'ky',
  Lao: 'lo',
  Latin: 'la',
  Latvian: 'lv',
  Lingala: 'ln',
  Lithuanian: 'lt',
  Luganda: 'lg',
  Luxembourgish: 'lb',
  Macedonian: 'mk',
  Maithili: 'mai',
  Malagasy: 'mg',
  Malay: 'ms',
  Malayalam: 'ml',
  Maltese: 'mt',
  Maori: 'mi',
  Marathi: 'mr',
  'Meiteilon (manipuri)': 'mni-Mtei',
  Mizo: 'lus',
  Mongolian: 'mn',
  Myanmar: 'my',
  Nepali: 'ne',
  Norwegian: 'no',
  'Odia (oriya)': 'or',
  Oromo: 'om',
  Pashto: 'ps',
  Persian: 'fa',
  Polish: 'pl',
  Portuguese: 'pt',
  Punjabi: 'pa',
  Quechua: 'qu',
  Romanian: 'ro',
  Russian: 'ru',
  Samoan: 'sm',
  Sanskrit: 'sa',
  'Scots gaelic': 'gd',
  Sepedi: 'nso',
  Serbian: 'sr',
  Sesotho: 'st',
  Shona: 'sn',
  Sindhi: 'sd',
  Sinhala: 'si',
  Slovak: 'sk',
  Slovenian: 'sl',
  Somali: 'so',
  Spanish: 'es',
  Sundanese: 'su',
  Swahili: 'sw',
  Swedish: 'sv',
  Tajik: 'tg',
  Tamil: 'ta',
  Tatar: 'tt',
  Telugu: 'te',
  Thai: 'th',
  Tigrinya: 'ti',
  Tsonga: 'ts',
  Turkish: 'tr',
  Turkmen: 'tk',
  Twi: 'ak',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uyghur: 'ug',
  Uzbek: 'uz',
  // 'Vietnamese': 'vi',
  Welsh: 'cy',
  Xhosa: 'xh',
  Yiddish: 'yi',
  Yoruba: 'yo',
  Zulu: 'zu',
};

module.exports = LANGUAGE;
