const SENTENCE_STATUS = {
  CONFIRM: 'CONFIRM',
  UN_TRANSLATE: 'UN_TRANSLATE',
  REVIEW: 'REVIEW',
};

const PROJECT_STATUS = {
  INPROGRESS: 'INPROGRESS',
  CANCEL: 'CANCEL',
  FINISH: 'FINISH',
};

const PROJECT_ROLE = {
  PROJECT_MANAGER: 'PROJECT MANAGER',
  DEVELOPER: 'DEVELOPER',
  GUEST: 'GUEST',
  OWNER: 'OWNER',
};

module.exports = {
  SENTENCE_STATUS,
  PROJECT_STATUS,
  PROJECT_ROLE,
};
