const SENTENCE_STATUS = {
  CONFIRM: 'CONFIRM',
  UN_TRANSLATE: 'UN_TRANSLATE',
  REVIEW: 'REVIEW'
}

const PROJECT_STATUS = {
  INPROGRESS: 'INPROGRESS',
  CANCEL: 'CANCEL',
  FINISH: 'FINISH'
}

module.exports = {
  SENTENCE_STATUS,
  PROJECT_STATUS
}